"""empty message

Revision ID: 0357e5d9fe9c
Revises: ffdc0a98111c
Create Date: 2021-06-29 19:22:58.109869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0357e5d9fe9c'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('friendId', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['friendId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], )
    )
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('imgURL', sa.String(length=255), nullable=False),
    sa.Column('care', sa.Text(), nullable=False),
    sa.Column('light', sa.String(length=40), nullable=False),
    sa.Column('size', sa.String(length=40), nullable=False),
    sa.Column('difficulty', sa.String(length=40), nullable=False),
    sa.Column('variety', sa.String(length=60), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('plantId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plantId'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('greenhouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('plantId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plantId'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wishlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('plantId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plantId'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('first_name', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('imgURL', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'imgURL')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_table('wishlists')
    op.drop_table('greenhouses')
    op.drop_table('comments')
    op.drop_table('plants')
    op.drop_table('friends')
    # ### end Alembic commands ###
